name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v4

      - name: 2. Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 3. Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      - name: 4. Genera cartelle mancanti
        # Ho rimosso --force che causava l'errore 64
        run: flutter create --platforms=android .

      - name: 5. Installazione
        run: flutter pub get

      - name: 6. Compilazione
        run: flutter build apk --debug

      - name: 7. Scarica l'App
        uses: actions/upload-artifact@v4
        with:
          name: Volleygrade-App
          path: build/app/outputs/flutter-apk/app-debug.apk
